src/engineprocess.cpp
This lead to bugs/crashes on operating system which use a high concurrency setting. `select` only allowed up to 1024 FD. Instead replace it with the more robust `poll`
```
WARNING: select() can monitor only file descriptors numbers that
are less than FD_SETSIZE (1024)—an unreasonably low limit for
many modern applications—and this limitation will not change.
All modern applications should instead use [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html) or [epoll(7)](https://man7.org/linux/man-pages/man7/epoll.7.html),
which do not suffer this limitation.
```
=> replace select with poll

src/engines/uci_engine.cpp, src/options.cpp, tests/options_test.h
A bug in the option.X part of the engine options parsing was found, awaiting confirmation that the bug was fixed before merging.
=> Fix engine option parsing

src/tournament.cpp
Add extra info to the rating printing (most importantly the WLD %)
Example of the new output
```
Result of Alexandria-dev vs Alexandria-master: 4 - 0 - 6 (0.70)
Ptnml:        WW     WD  DD/WL     LD     LL
1      2      2      0      0
LLR: 0.00 [-2.94 ; 2.94]
Games:10 W:40.0% L:0.0% D:60.0%
Elo difference: 147.19 +/- 134.89
```
=> Add total number of games and WLD % to the rating printing

src/tournament.cpp, src/tournament.hpp
this makes findElement return an optional value, if the value isn't present it gets treated as  0 for pgn reporting and adjudication, it's a general fix for #93 with the downside of incomplete pgn output and broken adj for engines with more "exotic" formats. 
pgn of an engine that crashed with the previous behaviour
```
[Event "?"]
[Site "?"]
[Date "2023-03-15"]
[Round "5"]
[White "ApotheosisV1.0.1_Windows-2"]
[Black "SimpleAlex"]
[Result "0-1"]
[FEN "rnbqnrk1/ppp3bp/3p2p1/3Ppp2/2P1P3/2N1BP2/PP1Q2PP/R3KBNR w KQ f6 0 9"]
[GameDuration "00:00:19"]
[GameEndTime "2023-03-15T11:54:29 +0100"]
[GameStartTime "2023-03-15T11:54:10 +0100"]
[PlyCount "112"]
[TimeControl "8+0.08"]
1. Nge2 {+0.00/5 0.272s} f4 {+0.01/12 0.308s} 2. Bf2 {+0.00/5 0.263s} b6 {+0.01/12 0.849s} 3. O-O-O {+0.00/4 0.257s} Qf6 …
```
=> Make nodes depth and score parsing optional

src/options.cpp, src/options.hpp, src/pgn_builder.cpp, src/tournament.cpp, src/tournament_data.hpp
Adds the optional tracking of seldepth, in the same vain of the node tracking, closes #99 
sample pgn excerpt
```
4. g4 {+0.01/13 n=534769 sd=25 0.267s} d5 {+1.24/13 n=357486 sd=17 0.199s}
5. Qa4 {+0.01/15 n=628412 sd=25 0.350s} e4 {+1.95/14 n=600007 sd=20 0.315s} 
6. Qxb4 {+0.01/16 n=554187 sd=26 0.247s} exd3 {+1.75/15 n=214499 sd=15 0.128s}
7. Nd4 {+0.03/16 n=342371 sd=27 0.485s} Ne5 {+1.66/16 n=852862 sd=23 0.449s}
```
=> Add seldepth tracking

README.md, src/cli.cpp, src/engines/uci_engine.cpp, src/third_party/communication.hpp, tests/data/engine/dummy_engine.cpp
usage:
```
.\fast-chess.exe -engine cmd=random_mover name=random_move_1 \
-engine cmd=random_mover name=random_move_2 \
-each tc=2+0.02s args="single words \"multiple words\"" -rounds 1 -repeat -concurrency 4 \
-openings file=tests/e2e/openings.epd format=epd order=random
```` 
closes https://github.com/Disservin/fast-chess/issues/139
=> feat: implement engine args

src/third_party/communication.hpp
This section of code is not used on Windows and causes build failures
=> Minor build fix for windows

src/process/process_posix.hpp, src/process/process_win.hpp
while async itself also adds some overhead it seems that this is still an improvement over the PeekNamedPipe approach
=> refactor: improve windows readProcess speed

src/matchmaking/elo/elo.cpp, src/matchmaking/elo/elo.hpp, src/matchmaking/output/output_cutechess.hpp, src/matchmaking/output/output_fastchess.hpp
statistics functions are now overloaded so they can be called with pentanomial results. this would spit out pentanomial elo, error margins, draw ratio, score ratio, and LOS.
Edit: added better approximation for trinomial LOS since the last one by remi coulom doesnt include draw information and is made for convenience of calculation: https://www.talkchess.com/forum/viewtopic.php?t=51003&start=5 . Also replaced the entire phiinv function with the actual value for 95% confidence interval.
=> feat: replace trinomial stats with pentanomial stats

man, src/matchmaking/output/output_cutechess.hpp, src/matchmaking/output/output_fastchess.hpp, src/matchmaking/sprt/sprt.cpp, src/matchmaking/sprt/sprt.hpp, src/matchmaking/tournament/roundrobin/roundrobin.cpp
also flip the pentanomial output from 2-0 to 0-2 to be more consistent with fishtest and Openbench.
=> Set default SPRT mode to pentanomial

src/matchmaking/elo/elo.cpp, src/matchmaking/elo/elo.hpp, src/matchmaking/output/output_fastchess.hpp
Note: error margins for nElo are calculated differently from fishtest. in fishtest the skewness and excess kurtosis of the bell curve is taken into account while in here a perfect bell curve is assumed for ease of calculation. this makes it less accurate but the differences are very slight (probably around 0.1 elo at most).
output looks like this:
=> add nelo statistic and annotate WDL result in fastchess output

src/cli/cli.cpp, src/matchmaking/sprt/sprt.cpp, src/matchmaking/sprt/sprt.hpp, src/matchmaking/tournament/roundrobin/roundrobin.cpp, src/types/tournament_options.hpp
since we're now using normalized elo bounds for sprt to be similar to fishtest and openbench, i wanted to add the option for users to instead use logistic elo bounds if they prefer that more. so we can add a parameter to the options to specify if they want to use normalized or logistic bounds like this:
```-sprt elo0=ELO0 elo1=ELO1 alpha=ALPHA beta=BETA bounds=(logistic/normalized)```
unfortunately idk how the options and parsing code in cli.cpp works, maybe you can help me out? @Disservin
=> optional parameter for logistic elo SPRT bounds

src/types/tournament_options.hpp
set default movecount for adjudication to 1
=> fix bug where games are instantly adjudicated when movecount key is not specified

src/matchmaking/tournament/base/tournament.hpp, src/matchmaking/tournament/roundrobin/roundrobin.cpp, src/matchmaking/tournament/roundrobin/roundrobin.hpp
fixes issue https://github.com/Disservin/fast-chess/issues/244
fixed output:
```
C:\Users\Gahtan Syarif Nahdi\Downloads\fast-chess-matchcount5\fast-chess-matchcount5>fast-chess.exe -openings file=openingss.epd format=epd order=sequential -engine cmd=Stockfish-dev-20240413-c55ae376.exe name=Engine1 -engine cmd=Stockfish-dev-20240413-c55ae376.exe name=Engine2 -each tc=10+0.1 -rounds 4 -concurrency 4 -resign movecount=1 score=600 -pgnout file=fastchess.pgn\
Starting tournament...
Started game 1 of 8 (Engine1 vs Engine2)
Started game 4 of 8 (Engine2 vs Engine1)
Started game 3 of 8 (Engine1 vs Engine2)
Started game 2 of 8 (Engine2 vs Engine1)
Finished game 4 (Engine2 vs Engine1): 1-0 {Engine1 loses by adjudication}
Started game 5 of 8 (Engine1 vs Engine2)
Finished game 1 (Engine1 vs Engine2): …
```
=> Fix matchcount resetting after saving and loading test

src/cli/cli.cpp
mostly just in case someone typos fischerandom into fischerrandom
=> fix: display error when variant specified doesnt exist

src/matchmaking/tournament/roundrobin/roundrobin.cpp
Actually I think the fix is rather easy, we can just enqueue the create_match function with the round parameters.
before: 
```
➜  fast-chess git:(master) ./fast-chess -openings file=openings.epd format=epd order=random -engine cmd=../Stockfish/src/stockfish name=stockfish -engine cmd=../Stockfish/src/stockfish name=stockfish2 -each tc=1+0.01 -rounds 10240000 -games 2 -concurrency 2 -resign movecount=1 score=600 -pgnout file=fastchess.pgn -srand 4555321
Starting tournament...
Started game 1 of 20480000 (stockfish vs stockfish2)
Started game 2 of 20480000 (stockfish2 vs stockfish)
Finished game 1 (stockfish vs stockfish2): 1-0 {stockfish2 loses by adjudication}
Started game 3 of 20480000 (stockfish vs stockfish2)
Finished game 2 (stockfish2 vs stockfish): 1-0 {stockfish loses by …
```
=> fix: huge memory consumption with large number of rounds

src/cli/cli.cpp, src/matchmaking/match/match.cpp, src/matchmaking/player.hpp, src/matchmaking/tournament/tournament_manager.cpp, src/types/tournament_options.hpp
I set the time control to 0 if its below 0 so it prevents negative time which i feel might lead to weird behavior,
and the way i see it, the timemargin is just an extra time after the actual time control that the engine is alloted, so after the move is made it shouldnt be part of the calculation for the final time after increment is added,
say an engine exceeded the timelimit by 250ms with a 1 second increment, this way the final time after the move should be 1 second instead of 750ms
fix https://github.com/Disservin/fast-chess/issues/285
=> feat: add -timemargin option

src/pgn/pgn_builder.cpp, src/types/match_data.hpp
correct order is: event-site-date-round-white-black-result. Also reformat date to YYYY.MM.DD. cutechess also follows this standard. see below:
=> fix: reformat pgn date tag and change pgn tag order to follow standard

src/matchmaking/player.hpp
i feel this part of the code:
```
if (tc.time_left == 0) {
return true;
}
```
is unnecessary and might lead to weird behavior where if the timeleft ever reaches zero, the updateTime function would perpetually return true and timeout would never happen and time increment wont be added
=> fix: revise updateTime

src/time/timecontrol.cpp, src/types/tournament_options.hpp, tests/pgn_builder_test.cpp
display TimeControl["-"] when there is no time control specified to be consistent with the PGN standard and rename the default event to Fast-Chess Tournament as it makes more sense as an event name
=> fix: modify pgn

src/matchmaking/player.hpp
send "go infinite" if tc=inf and tc, st, plies, and depth arent specified. i think this is best practice than just sending "go" which doesnt have a defined behavior
=> refactor: send go infinite

src/matchmaking/player.hpp
This patch is to cover cases where one engine uses a tc and the other doesnt. say if white uses tc of 10/0.1 while black uses fixed nodes=100000, the uci input for white now displays 
```go wtime 10000 winc 100``` 
instead of 
```go wtime 10000 btime 0 winc 100 binc 0```
i feel this makes more sense since the uci standard allows for only one sides tc to be input and this way the engine can assume its own values.
=> refactor: individualize white and blacks time control uci input

src/pgn/pgn_builder.cpp, tests/pgn_builder_test.cpp
i noticed in cutechess, during when white tc is different from black, they use WhiteTimeControl and BlackTimeControl tags. now the problem is these tags arent part of the pgn standard, so i dont know if we should abide by the standard or mimic cutechess. what do you think?
=> refactor: cutechess pgn time control format during time odds

src/book/opening_book.cpp, src/cli/cli.cpp, src/types/tournament_options.hpp
cutechess starts its starting offset from 1 while fastchess currently starts from 0 (cutechess start=1 is fastchess start=0 and etc...), this patch makes them consistent by having fastchess also start from 1.
=> fix: starting offset off by 1

src/main.cpp
fishtest uses that string to exit, see: https://github.com/official-stockfish/fishtest/blob/ee4cde1e36768ad573b1ea11b3e76c0376b0e2f6/worker/games.py#L939
=> refactor: change "finished tournament." to "finished match"

README.md
prevents the usage of CXX=clang
=> refactor: clearer compile instruction

src/util/logger/logger.hpp
this is what chatgpt says at least
```
Immediate Output: If you need to ensure that output appears immediately, such as in logging or real-time user interaction scenarios, std::flush can be useful. For example, after printing a prompt to the user, you might want to flush the stream to ensure the prompt appears right away:
```
=> refactor: flush logger output

src/cli/cli.cpp
adds support for `-pgnout FILE min` and allows `policy=round` input which fastchess has support for
=> refactor: improve compatibility with supported cutechess command

src/matchmaking/match/match.cpp
add comment on how fast-chess fixes a cutechess bug where epd versions of the same book gets adjudicated later compared to their pgn counterparts. to prevent someone from reverting it to the original cutechess version
=> chore: add comment

src/cli/cli.cpp, src/matchmaking/output/output_cutechess.hpp, src/matchmaking/output/output_fastchess.hpp, src/matchmaking/sprt/sprt.cpp, src/matchmaking/sprt/sprt.hpp, src/matchmaking/tournament/roundrobin/roundrobin.cpp, src/matchmaking/tournament/tournament_manager.cpp, src/types/tournament_options.hpp, tests/sprt_test.cpp
invalid sprt config now throws error instead of just a warning. it is better this way as the warning can easily be missed and the user would have realized too late, as can be seen here: https://discord.com/channels/435943710472011776/882956631514689597/1247264312066703420
already tested this patch and it works well
fix https://github.com/Disservin/fast-chess/issues/431
=> feat: throw error for invalid sprt config

src/matchmaking/tournament/tournament_manager.cpp
having alpha+beta >= 1 would cause bounds with flipped signs meaning the sprt test would immediatelyfinish
=> feat: add additional rule for sprt alpha and beta bounds

src/book/opening_book.cpp, src/book/opening_book.hpp
the current way of shrinking the vector is by relying on the shrink_to_fit() function to get rid of excess memory usage. this is not ideal since shrink_to_fit() is implementation defined and a non-binding request, so its completely up to the memory allocator how much memory it frees up. with this patch the shrinking is done using the vector swap trick where the vector is swapped with a temporary copy that immediately goes out of scope. this 100% ensures complete memory reduction.
here is a comparison of the memory usage in a match of 1000 rounds using UHO lichess book with shrink_to_fit() method and vector swap method:
shrink_to_fit():
vector swap trick:
as can be seen, the new method is much more effective and reliable.
=> refactor: better way of shrinking the book vector

src/engine/uci_engine.cpp, src/matchmaking/match/match.cpp, src/matchmaking/match/match.hpp, src/matchmaking/tournament/base/tournament.cpp
when passed `-recover` the engine that disconnected/crashed  will lose the game and the tournament continues with the next match and unresponsive engines are restarted
=> feat: reimplement recover option

app/src/cli/cli.cpp
this is how its used with the std::mt19937_64:
=> fix parseRandomSeed

app/src/engine/uci_engine.cpp, app/src/engine/uci_engine.hpp, app/src/matchmaking/output/output.hpp, app/src/matchmaking/output/output_cutechess.hpp, app/src/matchmaking/output/output_fastchess.hpp, app/src/matchmaking/tournament/base/tournament.cpp, app/src/matchmaking/tournament/base/tournament.hpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.hpp
its done
the only thing left is the uci default values, for that you can just replace the placeholder values here:
fix https://github.com/Disservin/fast-chess/issues/479
=> feat: display tc, hash, threads, and book in fastchess output

app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp
```
--------------------------------------------------
Results of engine1 vs engine2 (2+0.02, 1t, 16MB, book.epd):
Elo: -78.52 +/- 162.75, nElo: -86.86 +/- 160.50
LOS: 14.44 %, DrawRatio: 55.56 %, PairsRatio: 0.33
Games: 18, Wins: 7, Losses: 11, Draws: 0, Points: 7.0 (38.89 %)
Ptnml(0-2): [3, 0, 5, 0, 1]
LLR: -0.06 (-2.94, 2.94) [0.00, 5.00]
--------------------------------------------------
Warning; No bestmove found in the last line from engine1
Warning; No bestmove found in the last line from engine1
Warning; No info line found in the last line which includes the score from engine1
Warning; No info line found in the last line which includes the score from engine1
Warning; No info line found in the last line which includes the score from engine1
Warning; No info string found in the last …
```
=> fix: illegal moves when engine times out

app/src/time/timecontrol.cpp
basically we have a bug where game auto time losses if timemargin is not bigger than fixed_time because time_left_ is not reset after every move, this fixes that
=> fix: timelosses in fixed time mode when timemargin is not specified

app/src/cli/cli.cpp
missing parenthesis for the engine path validation https://github.com/Disservin/fast-chess/blob/2a4ffaf57857df102dad4a1efb51106190fbd0c7/app/src/engine/uci_engine.cpp#L183
issue https://github.com/Disservin/fast-chess/issues/528
=> fix: missing parenthesis on validateEnginePath

app/src/matchmaking/output/output_cutechess.hpp, app/src/matchmaking/sprt/sprt.cpp, app/src/matchmaking/sprt/sprt.hpp
looks like this for cutechess output:
```
SPRT: llr 2.98 (101.2%), lbound -2.94, ubound 2.94 - H1 was accepted
```
=> fix: make sprt result format consistent with cutechess output

app/src/matchmaking/output/output_fastchess.hpp
i think this is a useful stat for measuring if a book leans more to being too unbalanced or too balanced, if WL/DD>1 then we can infer that the book leans more to being unbalanced while WL/DD<1 means a book leans more to being balanced.
looks like this:
```
--------------------------------------------------
Results of random_move_1 vs random_move_2 (2+0.02, NULL, NULL, openings.pgn):
Elo: -34.86 +/- 62.20, nElo: -122.84 +/- 215.34
LOS: 13.18 %, DrawRatio: 80.00 %, PairsRatio: 0.00
Games: 10, Wins: 1, Losses: 2, Draws: 7, Points: 4.5 (45.00 %)
Ptnml(0-2): [0, 1, 4, 0, 0], WL/DD Ratio: 0.33
--------------------------------------------------
```
=> feat: add WL/DD Ratio to fastchess output

app/src/main.cpp, app/src/matchmaking/tournament/tournament_manager.hpp, app/src/types/tournament_options.hpp
move "Finished match" to after process have been stopped as it signals the program stopping for fishtest and also disable autosave and ratinginterval for USE_CUTE build
=> Fishtest fix

app/src/cli/cli.cpp
based on this https://github.com/Disservin/fast-chess/blob/450d70a9fa4773c0e1cac383fc13dce220ab0b57/app/src/engine/uci_engine.cpp#L185-L189
=> fix: use the correct path for validate engines

app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.hpp
tested at `-each tc=0.1+0.001`
```
Finished game 719 (sf1 vs sf2): 1-0 {White mates}
Finished game 765 (sf1 vs sf2): 1-0 {White mates}
Score of sf1 vs sf2: 322 - 336 - 83  [0.491] 741
Score of sf1 vs sf2: 323 - 336 - 83  [0.491] 742
```
fixes https://github.com/Disservin/fast-chess/issues/554
=> fix: avoid chaotic game output

app/src/matchmaking/tournament/roundrobin/roundrobin.cpp
prevent cases where finished game is printed twice before the scoreline, as this may affect fishtest parsing.
prevents this:
```
Finished game 64 (Engine2 vs Engine1): 1-0 {Black loses on time}
Finished game 63 (Engine1 vs Engine2): 1-0 {Black loses on time}
Score of Engine1 vs Engine2: 38 - 25 - 0  [0.603] 63
Started game 67 of 100 (Engine1 vs Engine2)
Score of Engine1 vs Engine2: 39 - 25 - 0  [0.609] 64
```
fix from https://github.com/Disservin/fast-chess/pull/569
=> fix: racy behavior for "Finished game" message

app/src/engine/process/process_win.hpp
`util::time::datetime_precise()` is a noticable bottleneck on windows
=> refactor: dont retrieve time when logging is disabled

app/src/matchmaking/output/output_cutechess.hpp
fix https://github.com/Disservin/fast-chess/issues/602
=> fix: sprt fmt wrong formatting when output format=cutechess

app/src/engine/process/process_posix.hpp
=> refactor: avoid adding potentially empty lines

app/src/matchmaking/match/match.cpp, app/src/pgn/pgn_builder.cpp, app/src/types/match_data.hpp, app/tests/pgn_builder_test.cpp
this is part of the pgn standard http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c9.8.1 goal is to make it easier to filter out normal matches with adjudications/disconnects/illegal moves etc...
=> refactor: add "normal" termination tag for pgn

app/src/engine/uci_engine.cpp, app/src/engine/uci_engine.hpp
engines need to answer to first uci within 5 seconds
=> refactor: split engine timeout times into 3 categories

app/src/pgn/pgn_reader.cpp, app/tests/data/test_invalid.pgn, app/tests/pgn_reader_test.cpp
fixes https://github.com/Disservin/fast-chess/issues/636
=> fix: correctly read book moves after an illegal move

app/src/util/helper.hpp
references https://github.com/Disservin/fast-chess/issues/634
=> fix: ignore empty strings when splitting a string

app/Makefile, app/src/engine/uci_engine.cpp, app/src/engine/uci_engine.hpp
Add a counting semaphore for the startup for the engines, up to 16 engines can be spawned simultaneously before having to wait for other engines to finish their initialization.initialization. This allows us to set a lower timeout threshold for the startup time on high core count machines, which will lag behind when spawning hundreds of engines near instantaneously.
=> refactor: introduce counting semaphore

app/src/time/timecontrol.cpp, app/tests/pgn_builder_test.cpp
fix case where `tc=0+inc` is displayed as `[TimeContol "+inc"]` in pgn
=> fix: pgn timecontrol formatting for 0 initial time

app/src/cli/cli.cpp, app/src/matchmaking/tournament/base/tournament.cpp, app/src/matchmaking/tournament/base/tournament.hpp, app/src/matchmaking/tournament/generator.hpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.hpp, app/src/types/tournament.hpp, app/src/util/threadpool.hpp
Saves memory and for very large round numbers by lazily creating the matches after they finish.
Pictures below are from a test tournament with 2 700 000 rounds.
=> refactor: match generator

app/src/matchmaking/tournament/roundrobin/match_generator.hpp
problem seem to have occured after the matchgenerator refactor
=> fix: games not continuing properly from last config savepoint

app/src/matchmaking/output/output_fastchess.hpp
`Ptnml(0-2): [0, 0, 1, 1, 0], WL/DD Ratio: infLLR: 0.02 (-2.94, 2.94) [0.00, 5.00]`
=> fix: missing newline between printElo and printSPRT

Makefile, app/Makefile, app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp, app/tests/match_test.cpp
i think this is the correct conversion?
based on SF's `auto m = (mate.plies > 0 ? (mate.plies + 1) : mate.plies) / 2;`
=> refactor: change pgn mate score format from moves to plies

app/src/matchmaking/match/match.cpp, app/tests/match_test.cpp
in cutechess when cp score is 0 the pgn comment has no sign:
`Qd6 {0.00/21 0.38s}`
=> refactor: pgn score format when cp is 0

app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp
In case the format is not matching the standard format, an illegal move will be raised.
fixes https://github.com/Disservin/fastchess/issues/705
=> fix: check uci format of engine bestmove

.gitignore, app/Makefile, app/compatability/spawn-check.mk, app/src/engine/process/process_posix.hpp
Solaris, macOS 10.15, glibc 2.29, freebsd 13.01
https://pubs.opengroup.org/onlinepubs/9799919799/functions/posix_spawn_file_actions_addchdir.html
fixes https://github.com/Disservin/fastchess/issues/699
=> fix: posix working directory for new c libraries

app/src/engine/uci_engine.cpp
After https://github.com/Disservin/fastchess/commit/b7f7c022415ed38a9134278ab56bb75f9a71b76e posix system were not able to use "dir" correctly anymore because the relative path didn't produce a result after the working directory was added.
=> fix: properly use working directory path when starting engine

app/src/cli/sanitize.cpp, app/src/core/logger/logger.cpp, app/src/engine/uci_engine.cpp, app/tests/doctest/doctest.hpp, app/tests/e2e/e2e.sh
As fastchess matures, maybe so should its error messages. ;)
=> avoid informal contractions in error messages

app/src/matchmaking/sprt/sprt.cpp, app/src/matchmaking/sprt/sprt.hpp, app/tests/sprt_test.cpp
Normalized elo only for commentry.
Happy to add logistic elo support if required.
=> Improve LLR algorithm

app/src/core/globals/globals.cpp, app/src/core/globals/globals.hpp, app/src/engine/process/process_posix.hpp, app/src/engine/process/process_win.hpp, app/src/engine/uci_engine.cpp, app/src/main.cpp, app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp, app/src/matchmaking/output/output.hpp, app/src/matchmaking/output/output_cutechess.hpp, app/src/matchmaking/output/output_fastchess.hpp, app/src/matchmaking/sprt/sprt.cpp, app/src/matchmaking/sprt/sprt.hpp, app/src/matchmaking/tournament/base/tournament.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.hpp, app/src/matchmaking/tournament/tournament_manager.cpp, app/src/types/tournament.hpp
A bunch of small quality-of-life features and fixes:
- Print a message if the SPRT has completed, and indicate whether H0 or H1 was accepted. Previously, the match would just end with no clear indication of why (unless you had logging enabled and reviewed the log). Ex.:
```
SPRT ([0.00, 100.00]) completed - H0 was accepted
```
- Print diagnostic messages for the following abnormal terminations: signal received, engine not responsive. Previously, these were only log messages, now they also show in the terminal. Ex.:
```
Received signal, stopping tournament.
```
- In case of an abnormal termination (such as SIGINT or an engine crashing without `-recover`): instead of printing 'finished match', print a message indicating that the tournament was interrupted, and automatically generate the …
=> Various QoL features and fixes

app/src/game/book/epd_reader.cpp, app/src/game/book/pgn_reader.cpp
This allows to specify the book names `foo.epd.gz` or `bar.pgn.gz`, and the files will be decompressed on the fly.
I find this feature very convenient, and it may allow to streamline the book handling for Fishtest in future.
If this is merged, some checks may need to be added to the CI to see that this works on all architectures (it should).
Also, it may be time to retire the `ZLIB` makefile flag and always compile with zlib support.
=> add support for gzipped books

app/src/engine/uci_engine.cpp, app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp, app/src/matchmaking/tournament/base/tournament.cpp
- Remove dot from log message.
- Give more log info.
- Terminate match early if refresh/start (ucinewgame) failed.
=> refactor: avoid double ucinewgame

app/src/game/pgn/pgn_builder.cpp
Not sure if this is the best way to implement this (and if you want to extend the cutechess compatibility behaviour to the PGN output).
=> Use "fischerandom" for PGN output in cutechess mode

app/src/game/book/pgn_reader.cpp, app/src/game/epd/epd_builder.hpp, app/src/game/pgn/pgn_builder.cpp, app/src/matchmaking/match/match.cpp
fixes the issue where
```
[Variant "From Position"]
[FEN "6k1/1p2p1rp/rP1pR3/2pP1pP1/p1P2P1P/R5K1/8/8 b - - 0 1"]
1... h5 2. Rh6 Rh7 3. Re6 Rg7 4. Rh6 Rh7 5. Re6 Rg7
```
is correctly adjudicated as a threefold repetition.
=> fix: exact ep square handling

app/Makefile, app/src/core/memory/cache.hpp, app/src/core/memory/scope_guard.hpp, app/src/matchmaking/tournament/base/tournament.cpp
tournament with 5 engines and 10 concurrency previously consuming 14.2G + 2.76G (swap) memory & potentially more.. with engines using restart option only 9.2G
=> refactor: free up engine cache with restart option

app/src/matchmaking/output/output_cutechess.hpp, app/src/matchmaking/output/output_fastchess.hpp
fixes https://github.com/Disservin/fastchess/issues/859
=> refactor: align multi engine output to longest engine name

app/src/matchmaking/match/match.cpp
FIDE rules state that a player _may_ claim a draw for both threefold repetitions and the 50 move rule, but it is not mandatory. Outputting pv moves past a threefold repetition and 50 quiet moves is thus not illegal, and fastchess should accordingly not warn if this happens.
=> Fix illegal pv warning

app/src/matchmaking/sprt/sprt.cpp
Fishtest terminates LLR calcuations after 10 iterations if it was not able to converge with the desired error. See: <https://github.com/official-stockfish/fishtest/blob/4f41ae1903df5e1de1fdb00f54c7c1410ac04dc9/server/fishtest/stats/LLRcalc.py#L86>
Do the same to avoid issue #877.
=> sprt: terminate LLR calculation after 10 iterations

app/src/cli/cli.cpp, app/src/cli/sanitize.cpp, app/tests/cli_test.cpp, man.md
not consistent with the other options
=> refactor!: remove extra dash for force-concurrency option

app/src/engine/process/iprocess.hpp, app/src/engine/process/process_posix.hpp, app/src/engine/process/process_win.hpp
previously engines received a sigkill immediately after a quit command, if this input wasn't transfered fast enough to the engine then the engine was immediately sigkilled which might prevent resource freeing.. instead wait 10s before an engine receives a sigkill after a quit
=> fix: wait 10s before sending sigkill to engine after quit

app/src/engine/uci_engine.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp
also move initialized higher so that engines dont wait for the kill timeout and instead first try to use "quit"
=> refactor: stop tournament when match creation threw exception

app/src/cli/cli.cpp, app/src/cli/sanitize.cpp
Exit right away if the engine isn’t found.
This makes the error message clearer by saying the executable doesn’t exist, rather than showing the previous generic one: "Fatal; <engine_name> engine startup failure: Couldn't start engine process."
=> fix: make sure the engine executable exists

app/src/matchmaking/tournament/base/tournament.cpp
=> fix: update engine pointers when engine crashes

app/src/affinity/cpuinfo/cpuinfo_win.hpp
According to Scott Meyers Effective Modern C++
**_Item 21: Prefer std::make_unique and std::make_shared to direct use of new._**
This is my first contribution, I have made sure the unit tests have passed.
=> refactor: replace raw new[] with std::make_unique in getCpuInfo

app/src/affinity/affinity.hpp
I understand this to produce identical results; and that gettid() is simply a wrapper for syscall(SYS_gettid) on Linux. I could be mistaken, so do check however you would normally.
=> bugfix: gettid is not available in older glibc versions
