Disservin/fastchess

src/engine_config.h, src/engineprocess.cpp, src/engineprocess.h, src/main.cpp, src/options.cpp, src/sprt.h, src/threadpool.h, src/tournament.cpp, src/tournament.h, src/uci_engine.cpp, src/uci_engine.h
ty and catch syscall and replace throws with a simple error notice, which can be used to check the status of the engine later.
Should close #46
=> recover engine

src/engines/engine_config.hpp, src/engines/engineprocess.cpp, src/engines/uci_engine.cpp, src/main.cpp, src/options.cpp, src/pgn_builder.cpp, src/tournament.cpp, src/tournament.hpp
Currently the support is fully functional but all the engines i've tested with struggle to keep up with timings precise up to 1ms and end up timing out, this PR shouldn't be merged until that problem is resolved
=> Movetime support

README.md, src/chess/board.cpp, src/chess/board.hpp, src/options.cpp, src/options.hpp, src/pgn_builder.cpp
add to the options `-pgnout notation=lan`
=> add lan notation option

src/chess/board.cpp, src/chess/board.hpp, src/chess/movegen.hpp, src/chess/perft.hpp, src/elo.cpp, src/elo.hpp, src/engines/uci_engine.hpp, src/logger.hpp, src/options.cpp, src/options.hpp, src/pgn_builder.hpp, src/sprt.hpp, src/tournament.cpp, src/tournament.hpp
- make board variables private
- use explicit constructors
- reorder class body
=> class cleanup

src/tournament.cpp
=> fix broken round reporting

src/matchmaking/roundrobin.cpp, src/matchmaking/roundrobin.hpp
- also fixes the shuffle for the pgn books from #150
=> refactor: shuffle

Makefile
- improved makefile for development reasons, probably makes it now unusable on misconfigured windows systems
=> refactor: makefile

src/matchmaking/output/output_fastchess.hpp
ensures output is flushed similar to the cutechess variant.
=> Add flushes to fast-chess output

third_party/chess.hpp
fixes https://github.com/Disservin/fast-chess/issues/215
=> fix: update chess lib

src/cli/cli.cpp, src/matchmaking/tournament/tournament_manager.cpp
trinomial stats will now be automatically outputted when -games is set to 1
=> fix: fixes bug where when -games is set to 1, no statistic will be outputted

src/engines/uci_engine.cpp, src/engines/uci_engine.hpp, src/matchmaking/match/match.cpp
=> fix: indefinite wait for bestmove after time loss

src/matchmaking/elo/elo.hpp, src/matchmaking/elo/elo_pentanomial.cpp, src/matchmaking/elo/elo_pentanomial.hpp, src/matchmaking/elo/elo_wdl.cpp, src/matchmaking/elo/elo_wdl.hpp, src/matchmaking/output/output_cutechess.hpp, src/matchmaking/output/output_fastchess.hpp, src/matchmaking/sprt/sprt.cpp
rename variables, remove unecessary functions, reduce amount of calculations. This should be the last of my refactors.
=> refactor: refactor statistics part 2

src/util/date.hpp
fix time issue in https://github.com/Disservin/fast-chess/issues/248
=> output local time in PGN

src/cli/cli.cpp, src/cli/cli.hpp
makes sure the score threshold is converted to positive in case someone inputs a negative eval
=> Makes sure score threshold is positive

src/matchmaking/match/match.cpp, src/pgn/pgn_reader.cpp, third_party/chess.hpp
@Disservin is this what you had in mind?
=> Epd implementation and update chess library

src/cli/cli.cpp
@Disservin i used the wrong variable here : https://github.com/Disservin/fast-chess/commit/8818f778848e3185e0c95da1fe5cd3209738784b
my bad 🙏
=> fix wrong variable

src/matchmaking/elo/elo.hpp, src/types/stats.hpp, tests/elo_test.cpp
closes https://github.com/Disservin/fast-chess/issues/243
=> test: add tests for elo models

src/matchmaking/book/opening_book.cpp, src/matchmaking/book/opening_book.hpp
fixes issue https://github.com/Disservin/fast-chess/issues/262 and https://github.com/Disservin/fast-chess/issues/259
=> enable -order=random and fix issue where idx exceeds book size for epd books

src/matchmaking/book/opening_book.hpp, src/matchmaking/tournament/tournament_manager.cpp, src/matchmaking/tournament/tournament_manager.hpp, src/util/rand.hpp
=> fix: correctly apply seed to prng

src/matchmaking/tournament/roundrobin/roundrobin.cpp
something like this `tournament_options_.report_penta ? round_id : game_id;` maybe has something weird to it
fixes #266
=> fix: reimplement ratinginterval change

src/matchmaking/book/opening_book.cpp, src/matchmaking/book/opening_book.hpp, src/pgn/pgn_reader.cpp, src/pgn/pgn_reader.hpp
=> feat: implement pgn reader limit for plies

src/cli/cli.cpp, src/epd/epd_builder.hpp, src/matchmaking/tournament/base/tournament.cpp, src/matchmaking/tournament/base/tournament.hpp, src/types/tournament_options.hpp
=> feat: add epdout

src/matchmaking/tournament/roundrobin/roundrobin.cpp
this way people would know the final llr in case they choose to disable ratinginterval
=> feat: display final LLR for SPRT results

src/pgn/pgn_builder.cpp, src/types/engine_config.hpp, tests/pgn_builder_test.cpp
fixes https://github.com/Disservin/fast-chess/issues/306
=> feat: print multiple different tc's in pgn

src/matchmaking/player.hpp
fixes https://github.com/Disservin/fast-chess/issues/302
=> fix: also check time left for fixed time per move

src/cli/cli.hpp
fixes https://github.com/Disservin/fast-chess/issues/311
=> fix: compilation error

src/matchmaking/player.hpp, src/types/engine_config.hpp
fixes https://github.com/Disservin/fast-chess/issues/310
=> fix: timelosses

src/matchmaking/player.hpp, src/types/engine_config.hpp
fixes https://github.com/Disservin/fast-chess/issues/328
=> fix: movestogo

src/matchmaking/tournament/tournament_manager.cpp
is this code correct? not sure
=> fix: prevent engine names being blank

src/cli/cli.cpp
cutechess users sometimes specify tc=10+0.1 as tc=inf/10+0.1 , this patch now supports that.
also adds support for cutechess style epdout where they use -epdout NAME instead of -epdout file=NAME
already tested it, works 👍 can safely merge
=> feat: support more cutechess style inputs

src/engine/uci_engine.cpp
fix issue https://github.com/Disservin/fast-chess/issues/354
havent tested it, but i think it works :P
=> fix: only parse multipv 1 info string

Makefile, third_party/chess.hpp
fixes https://github.com/Disservin/fast-chess/issues/369
=> fix: windows compilation

src/cli/cli.cpp, src/matchmaking/match/match.cpp, src/matchmaking/match/match.hpp, src/types/tournament_options.hpp
=> feat: make resignation same as cutechess resignation

src/engine/process/process_posix.hpp, src/engine/uci_engine.cpp, src/matchmaking/match/match.cpp
This reverts commit 6266e157297621deedba1ca3873bcde66f6bbb62.
=> Revert "Revert "refactor: remove exceptions from engine reading (#385)""

src/cli/cli.cpp, src/pgn/pgn_builder.cpp, src/types/tournament_options.hpp
this option exists in cutechess https://github.com/cutechess/cutechess/blob/master/docs/cutechess-cli.6.txt#L208
=> feat: add minimal output option for pgnout

src/cli/cli.cpp, src/matchmaking/match/match.cpp, src/pgn/pgn_builder.cpp, src/types/match_data.hpp, src/types/tournament_options.hpp
rebased since the last pr got merge conflicts. resolves https://github.com/Disservin/fast-chess/issues/400
=> feat: track hashfull and tbhits for pgn

src/cli/cli.cpp
try catch no longer works after latest refactor
=> fix exception handling

src/cli/cli.cpp
throw error when value is neither true nor false
=> feat: throw error for invalid boolean

README.md, src/cli/cli.cpp, src/matchmaking/tournament/tournament_manager.cpp
quick matches can now use pgn books
=> feat: add pgn book support for -quick option

tests/options_test.cpp
add new tests
fix https://github.com/Disservin/fast-chess/issues/437
=> chore: add tests for new cli options

src/pgn/pgn_builder.cpp
same as cutechess https://github.com/cutechess/cutechess/blob/1071d84cf272bd7deca0964336bf02e367e2b22b/projects/lib/src/pgngame.cpp#L473
=> PGN: add termination tag for disconnects

src/book/opening_book.cpp, src/book/opening_book.hpp, tests/opening_test.cpp
=> refactor: reduce opening book memory usage

app/src/matchmaking/match/match.cpp
closes https://github.com/Disservin/fast-chess/issues/477
=> feat: show fen position when encountering an illegal pv move

app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp, app/src/util/helper.hpp
fixes https://github.com/Disservin/fast-chess/issues/500
=> refactor: show illegal pv from startpos instead of current

app/src/cli/cli.cpp, app/src/time/timecontrol.hpp
already exists here: https://github.com/Disservin/fast-chess/blob/e6288fc0613c12017d5c22fa4101d1335f72c21a/app/src/time/timecontrol.hpp#L56
=> chore: get rid of redundant code

app/src/matchmaking/output/output_fastchess.hpp
=> refactor: formatting for missing uci default values

app/src/matchmaking/output/output.hpp, app/src/matchmaking/output/output_cutechess.hpp, app/src/matchmaking/output/output_fastchess.hpp
fix issue https://github.com/Disservin/fast-chess/issues/517
=> fix occasional weird output

app/tests/epd_builder_test.cpp
issue https://github.com/Disservin/fast-chess/issues/511
=> test: add unit tests for epdbuilder

app/src/pgn/pgn_builder.cpp
fixes https://github.com/Disservin/fast-chess/issues/523
=> fix: pgn annotation for illegal moves

app/src/matchmaking/sprt/sprt.cpp
my bad
fix commit https://github.com/Disservin/fast-chess/commit/31adaed23d357c638ddbc32f71d7525a6989d3cc
=> fix: wrong bounds displayed for cutechess output

app/src/cli/cli.hpp
fixes https://github.com/Disservin/fast-chess/issues/526
=> feat: show "(compiled with cutechess output)" when compiled with cutechess output

app/src/types/opening.hpp
issue https://github.com/Disservin/fast-chess/issues/546
=> refactor: sequential book ordering for USE_CUTE build

app/src/cli/cli.cpp
fix https://github.com/Disservin/fast-chess/issues/531
=> fix: validate engine not throwing error

app/third_party/chess.hpp
https://github.com/Disservin/chess-library/pull/103
fixes https://github.com/Disservin/fast-chess/issues/559
=> fix: update chess library to 0.6.52

app/src/cli/cli.cpp, app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp, app/src/matchmaking/output/output.hpp, app/src/matchmaking/output/output_cutechess.hpp, app/src/matchmaking/output/output_fastchess.hpp, app/src/matchmaking/result.hpp, app/src/matchmaking/stats.hpp, app/src/matchmaking/tournament/base/tournament.cpp, app/src/matchmaking/tournament/base/tournament.hpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/pgn/pgn_builder.cpp, app/src/types/match_data.hpp, app/src/util/game_pair.hpp, app/tests/pgn_builder_test.cpp, app/tests/result_test.cpp
wip, needs some careful eyes if everything still makes sense, i.e. stats collection, elo calculation, penta stats, correct flip of engines etc
=> refactor: results map and match creation

app/src/book/opening_book.cpp, app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp, app/src/matchmaking/output/output_cutechess.hpp, app/src/matchmaking/sprt/sprt.cpp, app/src/matchmaking/tournament/tournament_manager.cpp, app/src/types/tournament.hpp
improve cutechess compatibility
=> refactor: make output exactly the same as cutechess

app/src/matchmaking/tournament/base/tournament.cpp, app/tests/e2e/e2e.sh
improve cutechess output compatibility
=> refactor: change "saved results." message to logger::trace (ci error can be ignored)

app/src/cli/cli.cpp, app/src/cli/cli.hpp, app/src/matchmaking/scoreboard.hpp, app/src/matchmaking/tournament/base/tournament.cpp, app/src/matchmaking/tournament/base/tournament.hpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.hpp, app/tests/scoreboard_test.cpp
=> refactor: rename result to scoreboard

app/src/engine/uci_engine.cpp, app/src/time/timecontrol.cpp, app/src/time/timecontrol.hpp, app/tests/player.cpp
fixes https://github.com/Disservin/fast-chess/issues/561
=> test: add test for player

app/src/cli/cli.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/types/tournament.hpp, man
adding this for the sake of cutechess consistency https://github.com/cutechess/cutechess/blob/1071d84cf272bd7deca0964336bf02e367e2b22b/docs/cutechess-cli.6.txt#L225
edit: also fix bug where colors doesnt swap when you specify `-games 1`
=> feat: add noswap option from cutechess + fix: colors not swapping when -games 1

app/src/config/sanitize.cpp
fixes https://github.com/Disservin/fast-chess/issues/582
=> fix: gcc 7.3.0 compilation

.github/workflows/cutechess_tests.yml, .github/workflows/fastchess.yml, app/tests/cutechess/cutechess.sh
basic testing checking that the finished game state matches, and the game ply count matches.
=> Add cutechess compatibility testing to CI

app/src/engine/option/button_option.hpp, app/src/engine/option/check_option.hpp, app/src/engine/option/combo_option.hpp, app/src/engine/option/option_factory.hpp, app/src/engine/option/options.hpp, app/src/engine/option/spin_option.hpp, app/src/engine/option/string_option.hpp, app/src/engine/option/ucioption.hpp, app/src/engine/uci_engine.cpp, app/src/engine/uci_engine.hpp, app/src/matchmaking/output/output_fastchess.hpp, app/tests/e2e/e2e.sh, app/tests/mock/engine/dummy_engine.cpp, app/tests/mock/engine/random_mover.cpp
fixes https://github.com/Disservin/fast-chess/issues/535
=> feat: verify uci options

app/third_party/chess.hpp
prevent incorrect parsing of epd
fixes https://github.com/Disservin/fast-chess/issues/586
=> fix: update chess lib 0.6.54

app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp
no longer needed now that checkmates are prioritized
=> refactor: remove unecessary conditional

app/src/pgn/pgn_builder.hpp, app/tests/pgn_builder_test.cpp
fixes https://github.com/Disservin/fast-chess/issues/594
=> refactor: remove comma from pgns

app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp
fixes https://github.com/Disservin/fast-chess/issues/587
=> refactor: reorder game outcome precedence

app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp
fix https://github.com/Disservin/fast-chess/issues/587
=> fix: remaining differences between cutechess and fastchess

app/src/globals/globals.cpp, app/src/util/threadpool.hpp
fixes https://github.com/Disservin/fast-chess/issues/600
=> fix: prevent segfault at match end

app/third_party/chess.hpp
fixes https://github.com/Disservin/fast-chess/issues/604
=> chore: update chess-lib to 0.6.55

app/Makefile
successfully compiles
fix https://github.com/Disservin/fast-chess/issues/562
=> refactor: remove find command and hardcode source and header files in the makefile

app/src/cli/cli.cpp, app/src/types/tournament.hpp, app/src/util/rand.hpp, app/tests/options_test.cpp
this fixes it, no variable in the struct
=> fix: seed not getting randomized (ver 2)

app/src/cli/cli.cpp, app/src/engine/uci_engine.cpp, app/src/main.cpp, app/src/matchmaking/match/match.cpp, app/src/matchmaking/tournament/base/tournament.cpp, app/src/types/log.hpp, app/src/types/tournament.hpp
fixes https://github.com/Disservin/fast-chess/issues/619
=> fix: persist log info in config

app/src/config/sanitize.cpp, app/src/engine/process/iprocess.hpp, app/src/engine/process/process_posix.hpp, app/src/engine/process/process_win.hpp, app/src/engine/uci_engine.cpp, app/src/engine/uci_engine.hpp, app/src/globals/globals.cpp, app/src/matchmaking/match/match.cpp, app/tests/e2e/e2e.sh, app/tests/mock/engine/missing_shebang.sh
fails now on the example from https://github.com/Disservin/fast-chess/issues/623
=> feat: check if engine was properly started

app/src/config/sanitize.cpp, app/src/engine/uci_engine.cpp, app/src/matchmaking/output/output_fastchess.hpp, app/src/matchmaking/player.hpp, app/src/time/timecontrol.cpp
https://github.com/cutechess/cutechess/blob/780065637f9936bc29cc592c6f0b2007ccbf66de/projects/lib/src/timecontrol.cpp#L221
its also part of fide rules ex. https://www.youtube.com/watch?v=d-7ZpPDrOOo
=> fix: apply increment before the first move

.github/workflows/unit_tests.yml
Reproduces fishtest CI failure on master
=> Add unit tests under windows clang

app/src/pgn/pgn_reader.cpp, app/tests/data/test_invalid.pgn, app/tests/pgn_reader_test.cpp
fixes https://github.com/Disservin/fast-chess/issues/607
=> fix: respect game end during pgn reading

app/src/engine/uci_engine.cpp
fixes https://github.com/Disservin/fast-chess/issues/650
=> fix: duplicated log lines

app/src/engine/process/iprocess.hpp, app/src/engine/process/process_posix.hpp, app/src/engine/process/process_win.hpp, app/src/engine/uci_engine.cpp, app/src/time/timecontrol.cpp
This reverts commit b3415f41d7fa2a79535be24007aad2892999d8eb.
=> Revert "Revert "refactor: use status return type""

app/src/engine/process/process_posix.hpp
fixes https://github.com/Disservin/fastchess/issues/658
=> fix(posix): create process with all env variables

app/src/cli/cli.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/types/tournament.hpp, man
increase cutechess compatibility
=> feat: add -reverse option from cutechess

app/src/cli/cli.cpp, app/src/matchmaking/tournament/roundrobin/roundrobin.cpp, app/src/types/tournament.hpp, man
enhance cutechess compatibility
=> feat: add -wait option from cutechess

app/src/engine/uci_engine.cpp, app/src/engine/uci_engine.hpp, app/src/matchmaking/match/match.cpp, app/src/matchmaking/match/match.hpp, app/src/matchmaking/tournament/base/tournament.cpp, app/src/pgn/pgn_builder.cpp, app/src/types/match_data.hpp, app/tests/e2e/e2e.sh, app/tests/uci_engine_test.cpp
connection stalls is when engine doesnt respond to ping in time
fix https://github.com/Disservin/fastchess/issues/631
=> feat: add "connection stalls" termination

app/src/matchmaking/match/match.cpp
I dont think its good to have a logger message there, as it creates a couple hundred microsecond delay between fc sending the go command and fc starting the move countdown timer
=> Refactor: minimize delay

app/src/matchmaking/sprt/sprt.cpp, app/tests/sprt_test.cpp
added two more unit tests to take this into account
=> fix: sprt not ending when one side wins all games

app/src/engine/process/iprocess.hpp, app/src/engine/process/process_posix.hpp, app/src/engine/process/process_win.hpp, app/src/engine/uci_engine.cpp
references https://github.com/Disservin/fastchess/issues/524#issuecomment-2323163088
=> fix: properly set working dir on windows

app/src/pgn/pgn_builder.cpp, app/src/pgn/pgn_builder.hpp, app/tests/pgn_builder_test.cpp
fix https://github.com/Disservin/fastchess/issues/702
=> refactor: add comma to pgn

app/Makefile, app/src/main.cpp, app/src/printing/printing.cpp, app/src/printing/printing.h
fixes https://github.com/Disservin/fastchess/issues/711
=> fix(windows): set terminal output code

app/src/engine/compliance.hpp, app/src/engine/option/options.hpp, app/src/main.cpp
./fastchess --compliance ./random_mover
fixes https://github.com/Disservin/fastchess/issues/726
=> feat: add compliance check

app/src/cli/cli.cpp, app/tests/cutechess/cutechess.sh
doing this since gauntlet and other formats aren't supported yet
=> refactor: restrict tournament format to roundrobin

app/src/matchmaking/tournament/roundrobin/roundrobin.cpp
fixes https://github.com/Disservin/fastchess/issues/731
=> fix: ctrl c behavior

app/src/engine/process/anon_pipe.hpp, app/src/engine/process/iprocess.hpp, app/src/engine/process/process_posix.hpp, app/src/engine/process/process_win.hpp, app/src/engine/uci_engine.cpp, app/src/engine/uci_engine.hpp, app/src/matchmaking/match/match.cpp, app/tests/mock/engine/random_mover.cpp
Remove additional thread spawning which added some additional overhead and also was probably not working correctly in some circumstances.
=> refactor: windows Process::readProcess()

app/src/matchmaking/match/match.cpp
fixes https://github.com/Disservin/fastchess/issues/757
=> fix: pv verification for insufficient material position

app/src/engine/process/process_win.hpp
fixes https://github.com/Disservin/fastchess/issues/764
=> fix: dir no longer being able to use for path creation

app/src/engine/process/iprocess.hpp, app/src/engine/process/process_posix.hpp, app/src/engine/process/process_win.hpp
=> refactor: improve exit code status message on linux

app/third_party/chess.hpp
fixes a bug in the creation of a lan move
=> chore: update chess library to 0.7.6

app/third_party/chess.hpp
fixes a san generation bug which also affects the pgn writer
=> chore: update chess library

app/src/engine/process/process_win.hpp
fix excessive memory growth on windows when using berserk
=> fix: refactor windows process reading

app/src/cli/cli.cpp, app/src/cli/cli.hpp
fixes https://github.com/Disservin/fastchess/issues/810
=> fix: missing terminal output mode for help

app/src/affinity/affinity.hpp, app/src/affinity/cpuinfo/cpuinfo_win.hpp
On supported Windows platforms (Win11 or Server 2022), use newer APIs to set CPU affinity correctly when there are more than 64 logical CPUs.
Resolves Disservin/fastchess#816, at least for those newer Windows platforms.
With this change, running concurrency 64 on a 7980X (64 cores, 128 SMT threads) on Windows 11 and enabling CPU affinity now results in the expected CPU utilization:
As you can see, the first logical CPU of each of the 64 physical cores is now being utilized. This results in better and more consistent performance.
I've also validated that the app still works on Windows 10 (where `SetProcessDefaultCpuSetMasks` is not available), both with and without setting CPU affinity. Note that the Windows 10 system is a 4 core / 8 thread machine. I don't think testing on a >64 thread …
=> Add Windows support for CPU affinity for >64 CPUs.

app/src/matchmaking/match/match.cpp, app/src/types/match_data.hpp
=> fix: stoi exception when nps is too high

app/src/core/logger/logger.cpp, app/src/core/logger/logger.hpp
fixes https://github.com/Disservin/fastchess/issues/826
=> fix: compilation with zlib

app/src/game/book/opening.hpp, app/src/game/book/opening_book.cpp, app/src/game/book/pgn_reader.cpp, app/src/matchmaking/match/match.cpp, app/tests/opening_test.cpp, app/third_party/chess.hpp
fixes https://github.com/Disservin/fastchess/issues/830
=> fix: avoid crash with invalid opening book

Makefile
This is useful for some package managers on Linux.
=> Add DESTDIR support

app/src/cli/cli.cpp, app/src/matchmaking/tournament/gauntlet/gauntlet.hpp, app/src/matchmaking/tournament/tournament_manager.cpp, app/src/matchmaking/tournament/tournament_manager.hpp
fixes https://github.com/Disservin/fastchess/issues/889
=> fix: tournament type selection
